const vendedores = {
  "152": "AMANDA NABATE SARAIVA",
  "49": "ALICE PINTO DA SILVA",
  "42": "DANIELLA MODESTO DAS NEVES",
  "220": "INGRID BÁRBARA GONÇALVES FAVACHO",
  "151": "KARINA MARIA ASSUNÇÃO SANTOS",
  "17": "LUANA FERREIRA DOS SANTOS",
  "339": "RAFAELA ESTANISLAU AMARAL ALVES",
  "18": "RAFAELE DE SOUZA DA SILVA",
  "219": "RANGELLE AZEVEDO DA SILVA",
  "11": "SHEYLA BIANCA SOUSA DE OLIVEIRA",
  "210": "VITOR HUGO DA SILVA",
  "307": "HEBERT RILQUEM PAIVA DOS REIS"
};

const tecnicos = {
  "567": "ADNILDO SILVA DOS SANTOS",
  "19": "AFONSO ALEX SANTOS PRIMO",
  "809": "CARLOS PATRICK SILVA VIEIRA",
  "861": "CLEIDSON DE JESUS RODRIGUES",
  "46": "FLAVIO DOS REIS MENDES",
  "374": "GABRIEL VINICIUS MOURA BARBOSA",
  "881": "JESSÉ SANTOS DE ALCANTARA",
  "350": "MARIO GUILHERME NETO SANTOS PRIMO",
  "562": "RUBISMAR DOS ANJOS RODRIGUES",
  "16" : "TERCERIZADOS",

  // Ainda não identificados
  "861": "CLEIDSON DE JESUS RODRIGUES",
  "590": "JOHNATHAN CASTRO DOS REIS",
  "0": "SEM TÉCNICO"
};

module.exports = {
  vendedores,
  tecnicos
};